### ISSUE TITLE
Implement REST endpoints

### ISSUE THREAD

**Issue by ellykits** [matildahmariwa/Tafuta-restaurantFinder#3]
**In order to communicate with the front end we will need API endpoints exposed for the following:**

- [ ] Users/Login
- [ ] Reviews
- [ ] Restaurants
- [ ] Orders
- [ ] Menu
- [ ] Order status
- [ ] Image resources
- [ ] Menu category
- [ ] Payments

>Note: Each of the item maps to a model in the backend.

**Comment by matildahmariwa** [comment]
Will be done later
